#Basic
spring.application.name=demo.jwt
# Nombre de la aplicacion.
server.port = 8080
# El servidor web arrancará y escuchará en el puerto 8080.

#MYSQL
spring.jpa.hibernate.ddl-auto = update
# Actualiza automáticamente las tablas en la BD si haces cambios en tus entidades Java.
spring.datasource.url=jdbc:mysql://localhost:3306/multiservicespsidb?createDatabaseIfNotExist=true
# Ruta para conectarse a tu base de datos local.
spring.datasource.username = ${userMySQL}
# Usa la variable de entorno USER_MYSQL de tu PC como usuario (más seguro).
spring.datasource.password = ${passMySQL}
# Usa la variable de entorno PAS_MYSQL como contraseña de la base de datos.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Especifica el driver de conexión necesario para hablar con MySQL.

#Jap (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Indica el dialecto para que Hibernate genere SQL optimizado para MySQL.
spring.jpa.show-sql=true
# Imprime en la consola todas las consultas SQL que la aplicación hace por detrás.
spring.jpa.generate-ddl = true
# Activa la generación automática de la estructura de la base de datos (tablas, columnas) al arrancar.

#JWT
config.secretKey = ${claveJWT}

#Google
spring.security.oauth2.client.registration.google.client-id = ${idCliente}